# vocab
datapath: data/atec_nlp_sim_train.csv
trainpath: data/train.csv
testpath: data/test.csv
evalpath: data/poc_test.csv

# stopwords: data/stopwords_cn.txt
user_dict: data/user_dict.txt

# word2vec
embed: model/w2v/w2v.model

# model
seed: 10
n_kernels: 5
query_max_len: 20
target_max_len: 20
batch_size: 48
epochs: 16
learning_rate: 0.001
out_kernel: 128
max_grams: 3
device: cpu
saved_model: model/cknrm_model.pt

# logger setting
LogLevel_Console: 10
LogLevel_File: 10
LogFile: log/cknrm.log
LogFormat: '%(asctime)s|%(levelname)s:%(message)s'
